title: "Bark覺n Sar覺kartal"
author: "Bark覺n Sar覺kartal"
description: "Professional dumbass"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false         # show a sidebar instead of the usual header
minimal: true               # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
 # - {file: "index.html"}
 # - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:barkinsarikartal51@gmail.com"}
  - {title: Github, icon: github, url: "https://bit.ly/3xSCZTN"}
  - {title: Twitter, icon: twitter, url: "https://bit.ly/3yL9og3"}
  - {title: Spotify, icon: spotify, url: "https://spoti.fi/3xJiVTN"}
  - {title: Instagram, icon: instagram, url: "https://bit.ly/3g1KZvz"}
  - {title: LinkedIn, icon: linkedin, url: "https://bit.ly/2Ujqnr2"}
  - {title: YouTube, icon: youtube, url: "https://bit.ly/3fZWBPr"}
  - {title: Twitch, icon: twitch, url: "https://bit.ly/38u1hcs"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
